export default {
	home: 'Home',
	login: 'Login',
	logout: 'Logout',
	required: 'Required',
	unknown_error: 'Unknown error occurred',
	email: 'Email',
	password: 'Password',
	sign_up: 'Sign up',
	sign_in: 'Sign in',
	required_education: 'Required education',
	suitable_for: 'Suitable for',
	absolventySs: 'High school graduates',
	absolventyVs: 'College graduates',
	azylanty: 'Asylum seekers',
	bezbar: 'People in wheelchair',
	cizince: 'Foreigners',
	ozp: 'People with disabilities',
	settings: 'Settings'
};
