export default {
	home: 'Home',
	login: 'Login',
	logout: 'Logout',
	required: 'Required',
	unknown_error: 'Unknown error occurred',
	email: 'Email',
	password: 'Password',
	sign_up: 'Sign up',
	sign_in: 'Sign in',
	required_education: 'Required education',
	suitable_for: 'Suitable for',
	absolventySs: 'High school graduates',
	absolventyVs: 'College graduates',
	azylanty: 'Asylum seekers',
	bezbar: 'People in wheelchair',
	cizince: 'Foreigners',
	employment_type: 'Employment type',
	ozp: 'People with disabilities',
	ppvztahDpc: 'Contract for work',
	ppvztahDpp: 'Contract of services',
	ppvztahPpPlny: 'Full time',
	ppvztahPpZkrac: 'Part time',
	ppvztahSp: 'SP',
	shifts: 'Shifts',
	minimum_salary: 'Minimum salary',
	contact_person: 'Contact person',
	settings: 'Settings'
};
