export default {
	home: 'Domov',
	login: 'Prihlásenie',
	logout: 'Odhlásenie',
	required: 'Povinné pole',
	unknown_error: 'Nastala neznáma chyba',
	email: 'Email',
	password: 'Heslo',
	sign_up: 'Registrovať sa',
	sign_in: 'Prihlásiť sa',
	required_education: 'Požadované vzdelanie',
	suitable_for: 'Vhodné pre',
	absolventySs: 'Absolventi SŠ',
	absolventyVs: 'Absolventi VŠ',
	azylanty: 'Azylanti',
	bezbar: 'Osoby na vozíčku',
	cizince: 'Cudzinci',
	employment_type: 'Typ pracovného pomeru',
	ozp: 'Osoby so zdravotným postihnutím',
	ppvztahDpc: 'Dohoda o pracovnej činnosti',
	ppvztahDpp: 'Dohoda o vykonaní práce',
	ppvztahPpPlny: 'Plný úväzok',
	ppvztahPpZkrac: 'Skrátený úväzok',
	ppvztahSp: 'SP',
	shifts: 'Smeny',
	minimum_salary: 'Minimálna mzda',
	contact_person: 'Kontaktná osoba',
	settings: 'Nastavenia',
	show_more: 'Zobraziť viac',
	favorite_offers: 'Moje obľúbené ponuky',
	trending_offers: 'Trending ponuky',
	trending: 'Trending'
};
