export default {
	home: 'Domov',
	login: 'Prihlásenie',
	logout: 'Odhlásenie',
	required: 'Povinné pole',
	unknown_error: 'Nastala neznáma chyba',
	email: 'Email',
	password: 'Heslo',
	sign_up: 'Registrovať sa',
	sign_in: 'Prihlásiť sa',
	required_education: 'Požadované vzdelanie',
	suitable_for: 'Vhodné pre',
	absolventySs: 'Absolventi SŠ',
	absolventyVs: 'Absolventi VŠ',
	azylanty: 'Azylanti',
	bezbar: 'Osoby na vozíčku',
	cizince: 'Cudzinci',
	employment_type: 'Typ pracovného pomeru',
	ozp: 'Osoby so zdravotným postihnutím',
	ppvztahDpc: 'Dohoda o pracovnej činnosti',
	ppvztahDpp: 'Dohoda o vykonaní práce',
	ppvztahPpPlny: 'Plný úväzok',
	ppvztahPpZkrac: 'Skrátený úväzok',
	ppvztahSp: 'SP',
	shifts: 'Smeny',
	minimum_salary: 'Minimálna mzda',
	contact_person: 'Kontaktná osoba',
	settings: 'Nastavenia účtu',
	show_more: 'Zobraziť viac',
	favorite_offers: 'Moje obľúbené ponuky',
	trending_offers: 'Trending ponuky',
	trending: 'Trending',
	no_title: 'Bez názvu',
	no_description: 'Bez popisu',
	apply_filter: 'Aplikovať filter',
	profile_updated_success: 'Profilové informácie úspečne aktualizované.',
	profile_updated_error:
		'Počas aktualizovania profilových informácií nastala chyba.',
	personalized: 'Môj filter',
	offers: 'Ponuky',
	finish: 'Dokončiť',
	next: 'Ďalšie',
	back: 'Späť',
	Education: 'Vzdelanie',
	Field: 'Obor',
	Language: 'Jazyk',
	Shift: 'Smeny',
	Worker_Type: 'Vhodné pre',
	Salary: 'Mzda',
	newMail: 'Nový mail',
	newPassword: 'Nové heslo',
	passwordsDiffer: 'Heslá sa líšia!',
	repeatPassword: 'Zopakujte heslo',
	submit: 'Odoslať',
	Work_Relationship: 'Pracovný úväzok',
	hello: 'Dobrý deň',
	save: 'Uložiť'
};
